/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votingapp;

/**
 *
 * @author lenovo
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class welcomevote extends javax.swing.JFrame {

    /**
     * Creates new form welcomevote
     */
   int pid,vid;
   String area,fname;
    public welcomevote() {
        initComponents();
    }
    
    public welcomevote(int ii,String cty,String name) {
        initComponents();
            vid=ii;
            area=cty;
            fname=name;
       try{
           
           String q2="select * from tbvoter where id=?";
           myconnection obj1=new myconnection();
          PreparedStatement pst2=obj1.db.prepareStatement(q2);
          pst2.setInt(1,ii);
           ResultSet rs2=pst2.executeQuery();
           if(rs2.next())
           {
               String n = rs2.getString("fname");
               l1.setText("Welcome " + n);
           }
          
        String q1="select * from tbparty";
           
          myconnection obj=new myconnection();
          PreparedStatement pst=obj.db.prepareStatement(q1);
          ResultSet rs=pst.executeQuery();
          while(rs.next())
          { 
           c1.add(rs.getString("partyname"));
           
          
          }
          pid= rs.getInt("id");
       
       }
         
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
       
    }

       
            
        
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new java.awt.Label();
        c1 = new java.awt.Choice();
        button1 = new java.awt.Button();
        l2 = new java.awt.Label();
        l3 = new java.awt.Label();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setLabel("candidate");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        l2.setText("label1");

        l3.setText("label2");

        button2.setLabel("vote");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        try
        {
            int cid,partyi;
            String cname,cty,partname;
             partyi=pid;
               partname =  c1.getSelectedItem();
               cty=area;
           String q = "select * from tbparty where partyname=?";
          // String q = "select id,cand_name from tbcandidate where partyid=? and city=?";
                      
                    myconnection obj = new myconnection();
        PreparedStatement pst = obj.db.prepareStatement(q);
        //pst.setInt(1, partyi);
        pst.setString(1, partname);
        //pst.setString(2,cty);
        
        ResultSet rs = pst.executeQuery();
          if(rs.next())
          {   
              int pid = rs.getInt("id");
              String q1="select * from tbcandidate where partyid=? and city=?";
              PreparedStatement pst1 = obj.db.prepareStatement(q1);
              pst1.setInt(1,pid);
              pst1.setString(2,cty);
              ResultSet rs1 = pst1.executeQuery();
              if(rs1.next())
              {
              
              l2.setText(""+rs1.getString("cand_name"));
              l3.setText(""+rs1.getInt("id"));
              }
          }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
                                           
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
         try
        {
            int candId;
            String partname;
            //partyid=pid;
            candId = Integer.parseInt(l3.getText());
        String q ="select * from tbvoting where voterid=?";
        myconnection obj = new myconnection();
        PreparedStatement pst = obj.db.prepareStatement(q);
        pst.setInt(1, vid);
        ResultSet rs = pst.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(this,"Already voted");
        }
        else
        { 
            partname = c1.getSelectedItem();
            String p="select * from tbparty where partyname=? ";
            
          PreparedStatement pst2 = obj.db.prepareStatement(p);
        pst2.setString(1, partname);
        ResultSet rs2 = pst2.executeQuery();
        if(rs2.next())
        {
        String q5 = "insert into tbvoting(voterid,candidateid,partid)values(?,?,?)";
       // myconnection obj1 = new myconnection();
        PreparedStatement pst1 = obj.db.prepareStatement(q5);
        pst1.setInt(1, vid);
        pst1.setInt(3, pid);
        pst1.setInt(2,candId);
        pst1.executeUpdate();
        JOptionPane.showMessageDialog(this,"Thanks for voting");
        }
        }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
                                
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomevote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomevote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomevote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomevote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomevote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Choice c1;
    private java.awt.Label l1;
    private java.awt.Label l2;
    private java.awt.Label l3;
    // End of variables declaration//GEN-END:variables
}
